### ISSUE TITLE
Where is the examples directory?

### ISSUE THREAD

**Issue by CindyLinz** [khrt/graphql-perl#1]
as title..

**Comment by khrt** [comment]
There are no examples at the moment. I can recommend you take a look at tests, and https://github.com/khrt/graphql-perl/blob/master/t/harness.pm

**Comment by mohawk2** [comment]
The "other" graphql-perl has:
* a sample Dancer 2 applet: https://github.com/graphql-perl/sample-dancer2
* a sample Mojolicious applet: https://github.com/graphql-perl/sample-mojolicious

@CindyLinz I'd appreciate your thoughts!
